"""
Supabase Storage upload for PDFs generated by PDFGenerator.

Uses the project's lightweight httpx-based Supabase client (not supabase-py SDK)
to stay under Vercel's 250MB function size limit.
"""
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def upload_pdf_sync(
    pdf_bytes: bytes,
    *,
    filename: str,
    bucket: str = "nominations",
) -> str:
    """
    Upload pdf_bytes to Supabase Storage synchronously.
    Returns the public URL of the uploaded file.
    """
    from api._lib.database import get_supabase

    client = get_supabase()
    upload_path = filename.lstrip("/")
    file_options = {"content-type": "application/pdf", "upsert": "true"}

    try:
        client.storage.from_(bucket).upload(upload_path, pdf_bytes, file_options)
    except Exception:
        # If upload fails (e.g., file exists and upsert header not honored),
        # try removing first then re-uploading
        try:
            client.storage.from_(bucket).remove([upload_path])
        except Exception:
            pass
        client.storage.from_(bucket).upload(upload_path, pdf_bytes, file_options)

    return client.storage.from_(bucket).get_public_url(upload_path)
